name: Bitmap Allocator Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest] # figure out execution on windows runner
        config:
          - mapsize: 8
            indexsize: 16
          - mapsize: 8
            indexsize: 32
          - mapsize: 16
            indexsize: 16
          - mapsize: 16
            indexsize: 32
          - mapsize: 32
            indexsize: 32

    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        cmake . -B build \
          -DMAPSIZE=${{ matrix.config.mapsize }} \
          -DINDEXSIZE=${{ matrix.config.indexsize }} \
          -DBUILD_TESTS=ON

    - name: Compile with configured bitmaps and indexing
      # MAPSIZE=${{ matrix.config.mapsize }} INDEXSIZE=${{ matrix.config.indexsize }}
      run: cmake --build build --verbose

    - name: Run Unit Tests
      run: cd build/test/ && ./test_allocator

