name: Bitmap Allocator Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest] # figure out execution on windows runner
        config:
          - mapsize: 8
            indexsize: 16
          - mapsize: 8
            indexsize: 32
          - mapsize: 16
            indexsize: 16
          - mapsize: 16
            indexsize: 32
          - mapsize: 32
            indexsize: 32

    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake . -B build -DBUILD_TESTS=ON -DMAPSIZE=${{ matrix.config.mapsize }} -DINDEXSIZE=${{ matrix.config.indexsize }}

    - name: compile with with ${{ matrix.config.mapsize }}bit bitmaps and ${{ matrix.config.indexsize }}bit indexing
      run: cmake --build build

    - name: Run Unit Tests
      run: cd build/test/ && ./test_allocator

