name: Bitmap Allocator Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        config:
          - mapsize: 8
            indexsize: 16
          - mapsize: 8
            indexsize: 32
          - mapsize: 16
            indexsize: 16
          - mapsize: 16
            indexsize: 32
          - mapsize: 32
            indexsize: 32

    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2

    - name: Install Tools
      run: |
        sudo apt-get update

    - name: Build Allocator with ${{ matrix.config.mapsize }}bit bitmaps and ${{ matrix.config.indexsize }}bit indexing
      run: cd test && make run-test MAPSIZE=${{ matrix.config.mapsize }} INDEXSIZE=${{ matrix.config.indexsize }}