name: Bitmap Allocator Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2

    - name: Install Tools
      run: |
        sudo apt-get update

    - name: Build Allocator with 8bit bitmaps and 8bit indexing
      run: cd test && make run-test MAPSIZE=8 INDEXSIZE=16

    - name: Build Allocator with 8bit bitmaps and 16bit indexing
      run: cd test && make run-test MAPSIZE=8 INDEXSIZE=32

    - name: Build Allocator with 16bit bitmaps and 16bit indexing
      run: cd test && make run-test MAPSIZE=16 INDEXSIZE=16

    - name: Build Allocator with 16bit bitmaps and 32bit indexing
      run: cd test && make run-test MAPSIZE=16 INDEXSIZE=32

    - name: Build Allocator with 32bit bitmaps and 32bit indexing
      run: cd test && make run-test MAPSIZE=32 INDEXSIZE=32